server:
  port: 8082
spring:  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root  jpa:
    hibernate:      ddl-auto: update
    show-sql: true  application:    name: ORDER-SERVICE
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka#  mvc:#    pathmatch:#      matching-strategy: ANT_PATH_MATCHER
  
#  mvc:
#      pathmatch:
#            matching-strategy: ant_path_matcher